name: CI Budget Tracker

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  backend-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Run Backend Tests
        working-directory: ./budget-tracker-back
        run: |
          chmod +x mvnw
          ./mvnw clean test -Dspring.profiles.active=test

  frontend-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Préparer Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: 'budget-tracker-front/package-lock.json'
      - name: Installer dépendances Frontend
        working-directory: ./budget-tracker-front
        run: npm ci
      - name: Lancer les tests Frontend
        working-directory: ./budget-tracker-front
        run: npm test -- --watchAll=false --passWithNoTests
